# Generated by Django 5.2.8 on 2026-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
    ]
