# Generated by Django 5.2.8 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cadastro_complemento_cadastro_numero'),
        ('core', '0003_parametrosistema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cadastro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço (Rua/Av)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual (PJ)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social (PJ)'),
        ),
        migrations.AddConstraint(
            model_name='cadastro',
            constraint=models.UniqueConstraint(fields=('empresa', 'cpf'), name='unique_cpf_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='cadastro',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='unique_cnpj_por_empresa'),
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='endereco',
        ),
    ]
