# Generated by Django 5.2.8 on 2026-03-04 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_parametrosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Cargo')),
                ('cbo', models.CharField(blank=True, help_text='Código Brasileiro de Ocupações', max_length=10, null=True, verbose_name='CBO')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Função')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], default='SOLTEIRO', max_length=20, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=50, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naturalidade (Cidade/UF)')),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('rg_orgao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor/UF')),
                ('pis', models.CharField(help_text='Essencial para folha de pagamento', max_length=20, verbose_name='PIS/PASEP')),
                ('ctps_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Carteira de Trabalho')),
                ('ctps_serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série CTPS')),
                ('ctps_uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF CTPS')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CNH')),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria CNH')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Endereço (Rua/Av)')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('telefone_celular', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Pessoal')),
                ('data_admissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Admissão')),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Prestador de Serviço (PJ)'), ('TEMPORARIO', 'Temporário'), ('ESTAGIO', 'Estagiário')], default='CLT', max_length=20)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('FERIAS', 'Em Férias'), ('AFASTADO', 'Afastado (INSS/Licença)'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=20, verbose_name='Situação Atual')),
                ('horario_trabalho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de Trabalho')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta Corrente/Poupança')),
                ('pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('salario_contratual', models.DecimalField(blank=True, decimal_places=2, help_text='Salário registrado na carteira', max_digits=10, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.cargo', verbose_name='Cargo / Função')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Evento')),
                ('tipo', models.CharField(choices=[('ELOGIO', 'Elogio / Premiação'), ('ADVERTENCIA', 'Advertência'), ('SUSPENSAO', 'Suspensão'), ('ATESTADO', 'Atestado Médico'), ('FALTA', 'Falta Injustificada'), ('TREINAMENTO', 'Conclusão de Treinamento'), ('FERIAS_AGENDAMENTO', 'Agendamento de Férias'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Ocorrido')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('documento', models.FileField(blank=True, null=True, upload_to='funcionarios/ocorrencias/%Y/%m/', verbose_name='Documento/Evidência (PDF/Foto)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='rh.funcionario')),
            ],
            options={
                'verbose_name': 'Ocorrência / Histórico',
                'verbose_name_plural': 'Histórico do Funcionário',
                'ordering': ['-data'],
            },
        ),
    ]
