# Generated by Django 5.2.8 on 2026-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, help_text='Essencial para folha de pagamento', max_length=20, null=True, verbose_name='PIS/PASEP'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Prestador de Serviço (PJ)'), ('TEMPORARIO', 'Temporário'), ('ESTAGIO', 'Estagiário'), ('DIARISTA', 'Diarista / Avulso')], default='CLT', max_length=20),
        ),
    ]
