# Generated by Django 5.2.8 on 2026-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_funcionario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
    ]
