# Generated by Django 5.2.8 on 2026-04-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_planodecontas_unique_together'),
        ('rh', '0003_alter_funcionario_nome_mae'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='rh.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='conta',
            name='tipo_favorecido',
            field=models.CharField(choices=[('CADASTRO', 'Cliente / Fornecedor'), ('FUNCIONARIO', 'Funcionário (Folha / Adiantamento)')], default='CADASTRO', max_length=15, verbose_name='Tipo de Favorecido'),
        ),
    ]
