# Generated by Django 5.2.8 on 2026-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_conta_funcionario_conta_tipo_favorecido'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/contas/', verbose_name='Anexo / Comprovante'),
        ),
    ]
