# Generated by Django 5.2.8 on 2026-06-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_conta_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipo_favorecido',
            field=models.CharField(choices=[('CADASTRO', 'Cliente / Fornecedor'), ('FUNCIONARIO', 'Funcionário (Folha / Adiantamento)'), ('SIMPLES', 'Simples Nacional')], default='CADASTRO', max_length=15, verbose_name='Tipo de Favorecido'),
        ),
    ]
