# Generated by Django 5.2.8 on 2026-03-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_parametrosistema_chave'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa / Negócio')),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp / Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('origem', models.CharField(blank=True, help_text='Ex: Instagram, Indicação, Google', max_length=50, null=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo Lead (Não contatado)'), ('CONTATO', 'Em Contato / Qualificação'), ('AGENDADO', 'Visita ou Reunião Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('GANHO', 'Negócio Fechado (Ganho)'), ('PERDIDO', 'Negócio Perdido')], default='NOVO', max_length=20)),
                ('motivo_perda', models.TextField(blank=True, null=True, verbose_name='Motivo da Perda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Lead / Prospecto',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGACAO', 'Ligação Telefônica'), ('WHATSAPP', 'Mensagem (WhatsApp)'), ('EMAIL', 'E-mail'), ('VISITA', 'Visita Presencial'), ('REUNIAO', 'Reunião Online')], max_length=20)),
                ('data_agendada', models.DateTimeField(verbose_name='Data e Hora do Contato')),
                ('descricao', models.TextField(verbose_name='Assunto / Notas da Reunião')),
                ('realizada', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.funcionario', verbose_name='Responsável')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Interação / Agendamento',
                'verbose_name_plural': 'Agenda do CRM',
                'ordering': ['data_agendada'],
            },
        ),
    ]
