# Generated by Django 5.2.8 on 2026-03-07 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
        ('core', '0003_parametrosistema'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado / A Executar'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('FATURADO', 'Faturado (Nota Emitida)')], default='ORCAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('cliente', models.ForeignKey(limit_choices_to=models.Q(('situacao', 'ATIVO'), models.Q(('papel', 'CLI'), ('papel', 'AMB'), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente Solicitante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Pedido de Serviço',
                'verbose_name_plural': 'Pedidos de Serviços',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base (R$)')),
                ('unidade', models.CharField(choices=[('HORA', 'Por Hora'), ('DIA', 'Diária'), ('MES', 'Mensal')], default='HORA', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Catálogo de Serviço',
                'verbose_name_plural': 'Catálogo de Serviços',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início Previsto')),
                ('data_fim', models.DateTimeField(verbose_name='Fim Previsto')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Qtd (Horas/Dias)')),
                ('valor_total_item', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('realizado', models.BooleanField(default=False, verbose_name='Serviço Realizado?')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.funcionario', verbose_name='Profissional Alocado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='servicos.pedido')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.tiposervico', verbose_name='Serviço a Executar')),
            ],
            options={
                'verbose_name': 'Alocação de Profissional',
                'verbose_name_plural': 'Alocações',
            },
        ),
    ]
